Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -19,6 +19,17 @@ steps:
     ls -R MyConsoleApp
   displayName: 'List MyConsoleApp Contents'
 
+- script: |
+    if ! command -v docker &> /dev/null
+    then
+        echo "Docker could not be found"
+        exit 1
+    else
+        echo "Docker is installed"
+        docker version
+    fi
+  displayName: 'Check Docker Installation and Version'
+
 # Step 2: Build Docker Image (with corrected context)
 - script: |
     docker build -t $(imageName):$(Build.BuildId) -f '$(Build.SourcesDirectory)/MyConsoleApp/Dockerfile' MyConsoleApp/
